name: Package script to exe

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'


jobs:
  package_to_exe:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386 
          wget -O - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
          sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ focal main' 
          sudo apt update
          sudo apt install --install-recommends winehq-stable

      - name: Install Windows Python & PyInstaller
        run: |
          wget https://www.python.org/ftp/python/3.7.4/python-3.7.4.exe
          wine python-3.7.4.exe /quiet InstallAllUsers=1 PrependPath=1
          wine python -m pip install pyinstaller

      - name: Package to exe
        run: |
          wine python -m pip install -r requirements.txt
          wine pyinstaller --onefile $(ls src/*.py)
          printf "\n\n\n$(ls -lR .)\n\n\n"
          mv dist/main.exe CheckInstall.exe
          rm -rf build dist main.spec

      - name: Package executables
        run: |
          mkdir -p archive
          cp run.cmd archive/
          cp CheckInstall.exe archive/
          cp README.md archive/
          cp RunAsTI.cmd archive/
          cp LICENSE archive/
          cd archive/
          zip CheckInstall.zip *
          mv CheckInstall.zip ../

      - name: Upload .zip package artifact
        uses: actions/upload-artifact@v3
        with:
          name: CheckInstall
          path: CheckInstall.zip
          if-no-files-found: error
